export { TabsViewContentDirective } from './tabs-view.directive'
export {PCTabsModule } from './tabs.module'
export {PCTabsComponent} from './tabs.component'
export {PCTabsViewComponent} from './tabs-view.component'
export {PCTabModelInterface,PCTabInterface,PCTabsViewInterface} from './tabs.model'